version: '3.7'
services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    ports:
      - "80:80"
      - "5000:5000"
    container_name: "gitlabcontainer"
#container host
  sonarqube:
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
    container_name: "sonarqubecontainer"
  jenkins:
    image: "jenkins/jenkins:latest"
    ports:
      - "8080:8080"
    container_name: "jenkinscontainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./thedata:/thedata
  registry:
    image: registry:2
    ports:
    - "6000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data  
      - ./registry/etc/docker:/etc/docker 
